### ISSUE TITLE
BMSimCUDA does not exist error while trying to cmake

### ISSUE THREAD

**Issue by sankethvedula** [sigurdstorve/OpenBCSim#110]
Hi, 

I tried compiling the src/CMakeLists.txt and it gave the following error.  

```
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.55.0
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
CMake Error at core/CMakeLists.txt:66 (install):
  install TARGETS given target "BCSimCUDA" which does not exist in this
  directory.
```
I have CUDA 8.0 already installed in my computer. 

Could you help me figure out what might be going wrong?
Thanks,
Sanketh

**Comment by sigurdstorve** [comment]
@sankethvedula Thanks for noticing! I have now corrected a mistake in the CMake setup. What happened was that the GPU parts were referenced even though GPU stuff were not enabled. Also I wrote down some notes on how to build on Windows. Hopefully they will be usable for Linux builds also. I'll add step-by-step instructions for compiling the GPU part also soon.

**Comment by sankethvedula** [comment]
Hi @sigurdstorve 

Thanks for the quick help! 

The cmake is smooth now. Could you point me to the notes that you were saying? 
I also did a cmake with the examples. I did not know how to run them though. Could you please point me to a few examples that helps me understand the software? 

Thanks again, 
Sanketh

**Comment by sigurdstorve** [comment]
@sankethvedula No problem! Thanks for trying out the code :smiley:

Basically, there are two ways to use it:
1. With the interactive Qt5 GUI where you can load a point-scatterer phantom and do scans. This application supports visualizing the phantom with the scan-sector, as well as showing log-compressed B-mode images.
1. Using the Python interface. There is a folder called "python" which contains some example scripts on how to use it. I have used those scripts to benchmark CPU vs GPU performance. These scripts have limited support for nice visualization, but shows how to use the simulator to generate IQ-data. 

There are some text files in the top-level with some more information. The file COMPILE_VISUAL_STUDIO.md has instructions for building (on Windows, but the steps should be similar on Linux). Also, I wrote down some notes on how to build & use the Python interface on Linux in HOWTO_PYTHON.md.

**Comment by sigurdstorve** [comment]
Here's a screenshot of the GUI application simulating a B-mode image of a left ventricle. To the left is the scan sector and the spheres illustrate point-scatterers. To the right is the simulated image. The phantom I used here is the file "generated_phantoms/lv_spline_model.h5". In the middle there is some controls to change sector width, tilt angle, etc.

![bcsimgui_example](https://cloud.githubusercontent.com/assets/7589059/21204892/d1fd9b22-c259-11e6-88d8-2183bcb55a35.png)
