### ISSUE TITLE
HDF5 issues in CMAKE

### ISSUE THREAD

**Issue by sankethvedula** [sigurdstorve/OpenBCSim#112]
Hi again @sigurdstorve 

Thanks for the detailed explanation of the software on the other thread :+1: 

I am trying to cmake the file now. I actually followed the following steps 
$ cmake .
$ sudo make install

But, later I tried to run the python script $python linear_scan_model.py - [along with the arguments mentioned in the HOW_TOPYTHON.md]

As expected it failed because, I didn't make the file like you suggested to do, i.e go into the cmake GUI and switch some variables to ON and subsequently when I tried to generate - It gave me the following error. 
` CMake Error at CMakeLists.txt:42 (message):
   Imported target hdf5-shared is not available
`  
My configuration file looks like follows:
`
```
 BCSIM_BUILD_BENCHMARK_CODE       OFF 
                                                                            
 BCSIM_BUILD_EXAMPLES             OFF
                                                                             
 BCSIM_BUILD_PYTHON_INTERFACE     ON                                                                              

 BCSIM_BUILD_QT5_GUI              OFF                                                                             

 BCSIM_BUILD_UNITTEST             OFF                                                                             

 BCSIM_BUILD_UTILS                ON                                                                              

 BCSIM_ENABLE_CUDA                OFF                                                                             

 BCSIM_ENABLE_NAN_CHECK           ON                                                                              

 BCSIM_ENABLE_OPENMP              ON                                                                              

 BUILD_SHARED_LIBS                ON                                                                              

 CMAKE_BUILD_TYPE                                                                                                 

 CMAKE_INSTALL_PREFIX             /usr/local                                                                      

 HDF5_C_LIBRARY_dl                /usr/lib/x86_64-linux-gnu/libdl.so                                              

 HDF5_C_LIBRARY_hdf5              /usr/lib/x86_64-linux-gnu/libhdf5.so                                            

 HDF5_C_LIBRARY_m                 /usr/lib/x86_64-linux-gnu/libm.so                                               

 HDF5_C_LIBRARY_pthread           /usr/lib/x86_64-linux-gnu/libpthread.so                                         

 HDF5_C_LIBRARY_z                 /usr/lib/x86_64-linux-gnu/libz.so                                               

 HDF5_DIR                         HDF5_DIR-NOTFOUND                                                               

```
`
As per hdf5, I generally use hdf5 files with Matlab (in Ubuntu 16.04) and also with other programming languages and it all works fine.
I could not understand what is raising this issue.
Could you please help me out with this?

**Comment by sigurdstorve** [comment]
@sankethvedula I think the reason is that CMake expects an imported target for HDF5 is available after calling ```find_package()```, which might only be true for recent versions of HDF5. I'll look into this issue the next days. I think it should be easy to fix. Thanks for noticing this issue!

**Comment by sigurdstorve** [comment]
@sankethvedula Now it seems to work fine on Ubuntu 16.04 using the official HDF5 libraries installed through Synaptic. The reason that I did not notice this problem was that I had built a very recent version of HDF5 from source myself, which *did* supply the imported targets.

Let me know if you run into more issues and I'll try to fix them :smile:

**Comment by saitta-s** [comment]
Hi @sigurdstorve, I'm having a similar problem with HDF5 which causes cmake to not generate the file pyrfsim.so. I installed the HDF5 libraries through Synaptic like you suggested, but I get the following warning: 

CMake Warning at CMakelists.txt:41 (message):
    Could not find imported HDF5 targets. Using module-mode instead.

Do you know why I get this warning? Everything else seems to work just fine, but I can't get past this issue. Any sort of help would be precious.
Thanks.
